"""empty message

Revision ID: ee705b40fc3c
Revises: f972fc6beccb
Create Date: 2025-10-08 20:46:09.236640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee705b40fc3c'
down_revision = 'f972fc6beccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('planet_galaxy_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('planet_self_conscious_especies_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('planet_self_conscious_especies_key'), ['self_conscious_especies'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('planet_galaxy_key'), ['galaxy'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
