"""empty message

Revision ID: ffa9bfcd0ad0
Revises: 8a3e22eecfb2
Create Date: 2025-10-07 08:56:03.705440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa9bfcd0ad0'
down_revision = '8a3e22eecfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', sa.String(length=280), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('age')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
